name: Build and Push to Repo-B

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:

    - name: Checkout this source code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build amd Commit files
      run: |
        npm install
        npm run build
        ls -la      
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: www
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
